# Generated by Django 3.0.3 on 2020-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='scores',
        ),
        migrations.AddField(
            model_name='game',
            name='final_scores',
            field=models.ManyToManyField(blank=True, to='scores.Score'),
        ),
    ]
